const routes = require('next-routes')

module.exports = routes()
  .add('Landing Page', '/', '/')
  .add('Login Page', '/login', '/login')
  .add('RegisterPage', '/register', '/register')
  .add('ForgetPassword', '/forget-password', '/forget-password')
  .add('ChangePassword', '/change-password/:token', '/change-password')
  .add('Dashboard', '/dasboard', '/dashboard')
  .add('Explore', '/explore', '/explore')

  .add('ModelCreate', '/create', '/model-create')
  .add('MeModelInfo', '/me/model/:id', '/me-model-info')
  .add('MeModelStats', '/me/model/:id/stats', '/me-model-stats')
  .add('MeModelDemo', '/me/model/:id/demo', '/me-model-demo')
  .add('MeModelBatch', '/me/model/:id/batch', '/me-model-batch')
  .add('MeModelAnno', '/me/model/:id/anno', '/me-model-anno')
  .add('MeModelTrain', '/me/model/:id/train', '/me-model-train')
  .add('MeModelSource', '/me/model/:id/source', '/me-model-source')

  .add('ModelInfo', '/model/:id', '/model-info')
  .add('ModelStats', '/model/:id/stats', '/model-stats')
  .add('ModelDemo', '/model/:id/demo', '/model-demo')
  .add('ModelBatch', '/model/:id/batch', '/model-batch')
  .add('ModelAnno', '/model/:id/anno', '/model-anno')
  .add('ModelTrain', '/model/:id/train', '/model-train')

  .add('AdminDashboard', '/admin', '/admin-dashboard')
  .add('AdminUser', '/admin/user', '/admin-user')
  .add('AdminSource', '/admin/source', '/admin-source')
  .add('AdminModel', '/admin/model', '/admin-model')